### ISSUE TITLE
Migration AddChoiceForeignKey doesn't work

### ISSUE THREAD

**Issue by lmatiolis** [thecartercenter/elmo#101]
The migration added on decb8f2f44203fc23af794ef5fa2cb4fcefbb879 doesn't work because the table `answers` is MyISAM. Reverting it to InnoDB makes the migration work, but i guess the change to MyISAM was planned, as seen [here](https://github.com/thecartercenter/elmo/blob/develop/db/migrate/20131112194557_convert_answers_to_my_isam.rb).

**Comment by hooverlunch** [comment]
Oops you're right. We need to add a migration to change it back. I did it
manually on the production machines to make sure it worked.

On Fri, Jul 31, 2015 at 6:14 PM, Leandro Matioli <notifications@github.com>
wrote:

> The migration added on decb8f2
> <https://github.com/thecartercenter/elmo/commit/decb8f2f44203fc23af794ef5fa2cb4fcefbb879>
> doesn't work because the table answers is MyISAM. Reverting it to InnoDB
> makes the migration work, but i guess the change to MyISAM was planned, as
> seen here
> <https://github.com/thecartercenter/elmo/blob/develop/db/migrate/20131112194557_convert_answers_to_my_isam.rb>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thecartercenter/elmo/issues/101>.
>



-- 
Tom Smyth

Worker-Owner, Sassafras Tech Collective
Specializing in innovative, usable tech for social change
sassafras.coop *·* @sassafrastech

Resident, Touchstone Cohousing
touchstonecohousing.org

**Comment by lmatiolis** [comment]
Issue is being tracked as 2768 on redmine.
