### ISSUE TITLE
Build failed using ruby-build

### ISSUE THREAD

**Issue by werdnanoslen** [thecartercenter/elmo#149]
I have an Ubuntu server running with all the requirements specified in the production installation guide, and everything was going well until this step:

```
elmo$ rbenv install `cat .ruby-version`
Downloading ruby-2.2.0.tar.gz...
-> https://dqw8nmjcqpjn7.cloudfront.net/7671e394abfb5d262fbcd3b27a71bf78737c7e9347fa21c39e58b0bb9c4840fc
Installing ruby-2.2.0...




BUILD FAILED (Ubuntu 14.04 using ruby-build 20150928-2-g717a54c)

Inspect or clean up the working tree at /tmp/ruby-build.20151013161520.2198
Results logged to /tmp/ruby-build.20151013161520.2198.log

Last 10 log lines:
make[3]: Leaving directory `/tmp/ruby-build.20151013161520.2198/ruby-2.2.0/ext/fiddle/libffi-3.2.1'
linking shared-object fiddle.so
/usr/bin/ld: ./libffi-3.2.1/.libs/libffi.a(raw_api.o): relocation R_X86_64_32S against `.rodata' can not be used when ma
king a shared object; recompile with -fPIC
./libffi-3.2.1/.libs/libffi.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [../../.ext/x86_64-linux/fiddle.so] Error 1
make[2]: Leaving directory `/tmp/ruby-build.20151013161520.2198/ruby-2.2.0/ext/fiddle'
make[1]: *** [ext/fiddle/all] Error 2
make[1]: Leaving directory `/tmp/ruby-build.20151013161520.2198/ruby-2.2.0'
make: *** [build-ext] Error 2
```

**Comment by hooverlunch** [comment]
This is a recent thing. Try `sudo apt-get install libffi-dev`. I have since
added this to the install instructions. Sorry for the trouble.

On Tue, Oct 13, 2015 at 4:16 PM, Andrew Nelson <notifications@github.com>
wrote:

> I have an Ubuntu server running with all the requirements specified in the
> production installation guide, and everything was going well until this
> step:
>
> elmo$ rbenv install `cat .ruby-version`
> Downloading ruby-2.2.0.tar.gz...
> -> https://dqw8nmjcqpjn7.cloudfront.net/7671e394abfb5d262fbcd3b27a71bf78737c7e9347fa21c39e58b0bb9c4840fc
> Installing ruby-2.2.0...
>
> BUILD FAILED (Ubuntu 14.04 using ruby-build 20150928-2-g717a54c)
>
> Inspect or clean up the working tree at /tmp/ruby-build.20151013160128.21322
> Results logged to /tmp/ruby-build.20151013160128.21322.log
>
> Last 10 log lines:
> make[3]: Leaving directory `/tmp/ruby-build.20151013160128.21322/ruby-2.2.0/ext/fiddle/libffi-3.2.1'
> linking shared-object fiddle.so
> /usr/bin/ld: ./libffi-3.2.1/.libs/libffi.a(raw_api.o): relocation R_X86_64_32S against `.rodata' can not be used when ma
> king a shared object; recompile with -fPIC
> ./libffi-3.2.1/.libs/libffi.a: error adding symbols: Bad value
> collect2: error: ld returned 1 exit status
> make[2]: *** [../../.ext/x86_64-linux/fiddle.so] Error 1
> make[2]: Leaving directory `/tmp/ruby-build.20151013160128.21322/ruby-2.2.0/ext/fiddle'
> make[1]: *** [ext/fiddle/all] Error 2
> make[1]: Leaving directory `/tmp/ruby-build.20151013160128.21322/ruby-2.2.0'Write failed:
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thecartercenter/elmo/issues/149>.
>



-- 
Tom Smyth

Worker-Owner, Sassafras Tech Collective
Specializing in innovative, usable tech for social change
sassafras.coop *·* @sassafrastech

Resident, Touchstone Cohousing
touchstonecohousing.org

**Comment by werdnanoslen** [comment]
Whew, thanks, I was about to dig through the build instructions to recompile with that -fPIC flag. But then that resulted in an error from this issue: https://github.com/sstephenson/ruby-build/issues/729. I took the suggestion there (https://github.com/sstephenson/ruby-build/issues/729#issuecomment-77776590) about disabling the doc installation, and it worked. I guess my server doesn't have enough memory to install the whole package?
