### ISSUE TITLE
Nemo?

### ISSUE THREAD

**Issue by trycrmr** [thecartercenter/elmo#447]
Hi there! I just stood up the application locally and the branding says "Nemo" instead of "Elmo". What does Nemo stand for?

**Comment by trycrmr** [comment]
Hahaha, understood! Thanks! 

A related side note, is there documentation about the user interface somewhere I have not come across yet? Or if that documentation doesn't exist is that an opportunity for a open source contribution to the project?

**Comment by smoyth** [comment]
Yes http://elmo-nemo.readthedocs.io/

It's under heavy development right now. Contributions are certainly welcome.
