### ISSUE TITLE
Failure to authenticate with admin user when submitting via ODK Collect

### ISSUE THREAD

**Issue by trycrmr** [thecartercenter/elmo#451]
Hello again! To validate using ODK Collect to obtain form submissions I connected to the server using the admin credentials generated by ELMO. I am able to get the forms from the server, fill out the form, and save it. When I attempt to "Send Finalized Form" I get an "Error: Moved Permanently (301) at https://[our url].com/m/missionname/deviceID=imei%3A[random numbers]". The server logs indicate the 301 is because the user submitting the form is not authenticated, and therefore being redirected to the login page. Below is a screenshot of the logs. 

![screen shot 2018-06-06 at 4 33 28 pm](https://user-images.githubusercontent.com/6002123/41066395-ab71efea-69af-11e8-85d5-ba27ee56c50d.png)

I've tried different users (staffers) and different devices. Any guidance would be much appreciated! 

Update: In re-reading the initial issue description I realized an implicit assumption I am making here is the admin user would have the necessary permissions.

**Comment by smoyth** [comment]
Ok I don't have a quick answer for you but a couple of things to note:

1. The logs show a normal sequence: a first HEAD request with a 401 (NOT 301) response, which results in another HEAD with the credentials being specified (you can see that in the second HEAD, the admin user is loaded) and a 204 response (meaning the HEAD request succeeded).
1. The logs don't actually show a 301 at all, so I'm not sure this is the correct log passage for the error you pasted.
1. The URL you posted is not a correct submission URL. It should end in `/submission`. So something might be messed up in your settings.

Have you tried using the barcode feature to configure your phone? I bet it would fix all these issues. If you reset your password you should have the option of displaying a barcode. See [here](https://opendatakit.org/2017/06/configure-collect-on-many-devices-with-qr-codes/) for how to use it in ODK.

**Comment by trycrmr** [comment]
Thanks! I will try that and get back to you! Considering #2 & #3, they're all my mistakes, the way you described it is what I was seeing. Re: #2 - I meant to write 302. For the URL, I forgot the /submission. I'm a little sick & delirious at the moment :-)

**Comment by trycrmr** [comment]
There ended up being a few problems, but I was the source of all of them and have found resolutions :-) . Thanks for the assistance!
